### ISSUE TITLE
deCONZ no longer start, address already in use

### ISSUE THREAD

**Issue by fredrikbaberg** [home-assistant/addons#1827]
## The problem

Since yesterday the deCONZ addon does not start. The main change was that I upgraded to Home Assistant 2021.2.1 (then 2021.2.2 since it did not work) and Home Assistant OS 5.11. Revert to Home Assistant OS 5.10 and Home Assistant 2021.2.0 does not help.

## Environment

- Add-on with the issue: core_deconz
- Add-on release with the issue: 5.3.2
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Home Assistant OS 5.11

## Problem-relevant configuration

```yaml
device: /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_<redacted ID>-if00-port0
vnc_password: ''
```
Under Network all ports are set to disabled.

## Traceback/Error logs

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
bind failed: Address already in use
error binding udev control socket
could not listen on fds: Invalid argument
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by fredrikbaberg** [comment]
Now I'm guessing, could there be an issue related to this: https://community.home-assistant.io/t/udevd-529-bind-fialed-address-in-use/278578/6 ? I do have the
`udevd[529]: bind failed: Address in use` `udevd[529]: error binding udev control socket` in the terminal of Home Assistant.
I haven't found an issue for that reported on GitHub yet, and am unsure which repository it should be created under.

**Comment by pvizeli** [comment]
Do you run the latest version of the add-on?

**Comment by fredrikbaberg** [comment]
> Do you run the latest version of the add-on?

I see no updates in my Home Assistant instance, but when I now looked at the changelog and `config.json` in the repository it confuses me, neither the version nor the changelog makes sense. See attached screenshot, it says I'm on 5.3.2 and the latest entry in the changelog is `Bump deCONZ to 2.05.75`.
![image](https://user-images.githubusercontent.com/19709460/107361620-f6704d80-6ad7-11eb-9211-e2d5072409a5.png)

This is what I see under Add-on Store, I think it should be the correct addon?
![image](https://user-images.githubusercontent.com/19709460/107362370-f290fb00-6ad8-11eb-994d-ef8a5e2400a0.png)

If I'm not on the latest version, that may explain the following lines in my supervisor log:
```
21-02-09 12:05:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of deCONZ
21-02-09 12:05:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of deCONZ
```

Would a reinstall of the addon be the correct next step?

**Comment by Dricey** [comment]
@fredrikbaberg It seems you are running a very old version of Deconz.

However I am running 6.6.5 which I upgraded this morning and I get the same error. Whenever I try to start Deconz it freezes the entire VM (Proxmox) and I have to kill it.

**Comment by fredrikbaberg** [comment]
@Dricey I find it odd that I'm running such an outdated version of deCONZ, even if I press "Reload" in the Add-on Store I see no available update and I frequently check to see that I'm on the latest version.

I had a look in the Home Assistant community thread I linked above and tried the "Check Home Assistant configuration" addon.
It runs, but I see the following in the log:
```
bind failed: Address in use
error binding udev control socket
```
It seems something else than deCONZ causes the issue.

I won't close this issue as @Dricey has the latest version and the same error.
Thank you @pvizeli for making me realize I'm on an old version of the addon. I'll wait for a reply here for a few hours before I attempt to reinstall the addon, to see if that gets me the latest version, in case you need any logs or other information from me.

**Comment by pvizeli** [comment]
The latest version of deconz don't use anymore a dbus. If you see `bind failed: Address in use` then you run not the latest version

**Comment by Dricey** [comment]
I think there is some sort of mix-up. I see the udevd message in the cli prompt from home assistant. Since I upgraded both Deconz and HA this morning. Whenever I start Deconz it crashes HA. So I don't see the message in the Deconz logging. I don't see anything because it becomes unresponsive

**Comment by fredrikbaberg** [comment]
I've now:
- Taken a snapshot of the deCONZ addon.
- Uninstalled the addon.
- Made four attempts from CLI with `addon reload` followed by `addon info core_deconz`, that is how many attempts it took me before latest version changed from 5.3.2 to 6.6.5.
- Installed latest version of addon, which started.
- Restored snapshot of addon, update to 6.6.5.
- Reset addon configuration (since I had `vnc_password` there).
- Power off and on machine, to make sure it still works.

After all this deCONZ now seem to work again. As a bonus, I found some "new" updates: MariaDB (from 2.1.2 to 2.2.1), Check Home Assistant configuration (3.2.0 to 3.6.0), Let's Encrypt (4.7.1 to 4.11.0).

I do see the `bind failed` at the login promt of the machine, but that may be an OS issue. If there is not already an issue for that I'll create one.

@pvizeli I'm OK with this issue being closed now since it works for me after the update.
There is still the issue @Dricey has, I'm not sure how to proceed with that.

**Comment by Dricey** [comment]
Close this item. My problems are also addressed in other topics I saw

**Comment by TheAlphaLaw** [comment]
FYI, this still occurs for me. Using Decons windows desktop app Phoscons. The connection between the conbee II and Home Assistant can't be made any longer.
