### ISSUE TITLE
DeConz 

### ISSUE THREAD

**Issue by wifiuk** [home-assistant/addons#2642]
I'm using DeConz 6.13 and 2022.4.7, rebooted the physical host and it appears so far to not have the same error message. So looking good. Thanks for the hard work getting this resolved!

_Originally posted by @wifiuk in https://github.com/home-assistant/core/issues/68165#issuecomment-1117573300_

This issue has returned with the latest version of home assistant.

**Comment by wifiuk** [comment]
![image](https://user-images.githubusercontent.com/3785545/187600446-3097ab57-6536-41d4-a519-83f042292aae.png)

**Comment by wifiuk** [comment]
have to remove it and re-add it again to get everything to work again

**Comment by marvindv** [comment]
I had the same problem after restarting my VM host. When I readded the integration I noticed that the internal IP address changed from 172.30.33.0 (as seen in the same error message in my logs) to 172.30.33.2 (as seen as the discovered deconz gateway in the Add Integration dialog). 

Interestingly, after I rolled back to a backup I created before readding the integration, everything worked fine again, with the old IP 172.30.33.0.

**Comment by mdegat01** [comment]
Are you trying to put that IP address in your config somewhere? If so, don't do that. The internal docker IP address isn't static. You can't bank on that being unchanging, you have to use the hostname for the container (`core-deconz`)

**Comment by wifiuk** [comment]
Something isn't right with deconz this was fixed before but has recently come back.

Any reboot causes this issue and have to delete and re add to get working.

No manual stuff is being done

**Comment by B3nihana** [comment]
Same issue here (Baremetal Rpi, no docker). Seems like the DHCP lease for the gateway isn't being released (i.e the previous IP address is still showing as reserved). Agree that this is relatively new, the latest Deconz release (2.18.2) doesn't show any relevant changes.

**Comment by JGNi** [comment]
Mine refuses. I can see it in the add-on. But inside deCONZ it will not connect to it. So frustrating.
![image](https://user-images.githubusercontent.com/26222087/192152937-0eaee4b5-06c7-49af-b19c-66303e75ba5f.png)
