### ISSUE TITLE
Terminal & SSH: FATAL: You need to setup a login!

### ISSUE THREAD

**Issue by zartmann** [home-assistant/addons#2762]
### Describe the issue you are experiencing

Not getting the server up and running with my ssh-rsa pub key that I generated on my mac using `ssh-keygen -b 4096 -t rsa `

I believe I've done the configuration according to the doc.

![Screenshot 2022-11-24 at 20 52 30](https://user-images.githubusercontent.com/49228094/203856379-36a5c365-128b-4045-bfa4-78027d765ce9.jpg)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

9.6.1

### Steps to reproduce the issue

1. Install add-on and configure the settings and restart the server.
...

### System Health information

 There are currently no repairs available 

### Anything in the Supervisor logs that might be useful for us?

```txt
There are no new issues!
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/apks.sh
cont-init: info: /etc/cont-init.d/apks.sh exited 0
cont-init: info: running /etc/cont-init.d/keygen.sh
[20:38:08] INFO: Restoring host keys...
cont-init: info: /etc/cont-init.d/keygen.sh exited 0
cont-init: info: running /etc/cont-init.d/profile.sh
cont-init: info: /etc/cont-init.d/profile.sh exited 0
cont-init: info: running /etc/cont-init.d/ssh.sh
[20:38:10] FATAL: You need to setup a login!
cont-init: info: /etc/cont-init.d/ssh.sh exited 1
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

Prior to configuring the ssh-rsa key, I was able to use the web cli interface.

**Comment by soffes** [comment]
I'm also seeing this same issue. If I don't set a password but set `authorized_keys` it will fail with `You need to setup a login!`. If I add a password, it works but I have to specify the password when sshing.

**Comment by romano21A** [comment]
I just had the same problem. The content of the editor window is included under `server:`, but `authorized_keys` needs to be at  top level. As a workaround you can "Edit on YAML" in the three-dots menu and add `authorized_keys` there

**Comment by snarman** [comment]
Thanks a bunch for the last comment. I'm completely new to Home Assistant and it took me hours to get ssh login with keys working cause it always failed with "You need to setup a login". The UI should really be fixed there.

**Comment by Chartreusito** [comment]
I confirm this configuration form is misleading cause i just had the same problem.
If authorized_keys is the recommanded way, it should be at the top of the page as a field, same as password is.
Using the edit yaml is working though.

**Comment by IGLOU-EU** [comment]
I confirm this issue, it should even be discouraged to use the password connection for security reasons

**Comment by ludeeus** [comment]
This is/was frontend bug, it is fixed here <https://github.com/home-assistant/supervisor/pull/4051> and will be included in the next Supervisor update.

**Comment by rastafarien** [comment]
closed ? still not easy in feb 23.
- in the YAML paste your public key between the brackets 
- in the ui  untick show disabled port and type in 22 (or change but fill  something)
- check the log to see if it's listenning on 0.0.0.0 on the right port
- login with ssh root@homeassistant -p 22   | optionnal if using default

**Comment by romanr** [comment]
hello from 1.5 years later.
@ludeeus this was closed and not tested perhaps?

- in message "you need to set up a login", "login" is jargon that could mean anything, I thought it refers to dedicated system user.
- configuring port disables web terminal this way!
- Documentation does not address how to successfully enable it.
- Everyone who ever want to set up terminal will google and go to this page for troubleshooting. hello!

**Comment by nrolland** [comment]
still an issue.

Workaround : from an empty config, edit the config through the yaml editor, then paste your key between the brackets at the authorized_keys entry, then save the config, and (re)start your service
