### ISSUE TITLE
Silicon Labs Multiprotocol crashing 

### ISSUE THREAD

**Issue by netzor** [home-assistant/addons#3446]
### Describe the issue you are experiencing

Add-on Silicon Labs Multiprotocol intermeditaly crashing daily on Home Assistant Yellow.
If watchdog is not enabled Zigbee and Thread devices stops working.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.4.4

### Steps to reproduce the issue

1.  The add-on seems to be crashing intermeditaly between 5-14 hours daily.
2.
3.
...

## System Information

version | core-2024.1.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Stockholm
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4988
Installed Version | 1.34.0
Stage | running
Available Repositories | 1388
Downloaded Repositories | 18
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Easee EV Charger</summary>

component_version | 0.9.55
-- | --
reach_easee_cloud | ok
connected2stream | true

</details>

<details><summary>Svensk Kollektivtrafikssensor (HASL)</summary>

Version | 3.1.1
-- | --
Schema | 3
Instances | 1
Database Size | 352 bytes
Startup in progress | false
Running tasks | false

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 458.4 GB
disk_used | 12.8 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Silicon Labs Multiprotocol (2.4.4), ESPHome (2023.12.9), Matter Server (5.0.4), Samba share (12.2.0), Terminal & SSH (9.8.1), SNMPD (0.2.3), Let's Encrypt (5.0.15), Mosquitto broker (6.4.0), NGINX Home Assistant SSL proxy (3.7.0), MQTT Explorer (browser-1.0.3), Tailscale (0.15.0), Piper (1.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 8
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 januari 2024 kl. 15:25
-- | --
current_recorder_run | 31 januari 2024 kl. 12:51
estimated_db_size | 271.36 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the add-on logs that might be useful for us?

```txt
otbr-agent[298]: 11:15:34.720 [N] MeshForwarder-:     dst:[fd01:ca3:4cac:1:e4b:2698:144e:939d]:47355
otbr-agent[298]: 11:15:37.718 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1076, chksum:d95a, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-67.0
otbr-agent[298]: 11:15:37.718 [N] MeshForwarder-:     src:[fd01:ca3:4cac:1:859c:98e4:58b0:91e]:5540
otbr-agent[298]: 11:15:37.718 [N] MeshForwarder-:     dst:[fd01:ca3:4cac:1:e4b:2698:144e:939d]:47355
otbr-agent[298]: 11:28:09.792 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1061, chksum:aac4, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-71.875
otbr-agent[298]: 11:28:09.793 [N] MeshForwarder-:     src:[fd01:ca3:4cac:1:859c:98e4:58b0:91e]:5540
otbr-agent[298]: 11:28:09.793 [N] MeshForwarder-:     dst:[fd01:ca3:4cac:1:e4b:2698:144e:939d]:47355
otbr-agent[298]: 11:28:16.790 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1058, chksum:5400, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-71.25
otbr-agent[298]: 11:28:16.790 [N] MeshForwarder-:     src:[fd01:ca3:4cac:1:859c:98e4:58b0:91e]:5540
otbr-agent[298]: 11:28:16.791 [N] MeshForwarder-:     dst:[fd01:ca3:4cac:1:e4b:2698:144e:939d]:47355
otbr-agent[298]: 11:28:18.793 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1058, chksum:5400, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-71.375
otbr-agent[298]: 11:28:18.794 [N] MeshForwarder-:     src:[fd01:ca3:4cac:1:859c:98e4:58b0:91e]:5540
otbr-agent[298]: 11:28:18.794 [N] MeshForwarder-:     dst:[fd01:ca3:4cac:1:e4b:2698:144e:939d]:47355
otbr-agent[298]: 11:35:57.176 [N] MeshForwarder-: Failed to send IPv6 UDP msg, len:90, chksum:df5d, ecn:no, to:0x5000, sec:yes, error:NoAck, prio:low
otbr-agent[298]: 11:35:57.177 [N] MeshForwarder-:     src:[fd01:ca3:4cac:1:e4b:2698:144e:939d]:47355
otbr-agent[298]: 11:35:57.177 [N] MeshForwarder-:     dst:[fd01:ca3:4cac:1:859c:98e4:58b0:91e]:5540
otbr-agent[298]: 11:36:55.101 [W] Platform------: Handle transmit done failed: Parse
otbr-agent: ../../third_party/openthread/repo/src/core/mac/sub_mac.cpp:624: void ot::Mac::SubMac::HandleTransmitDone(ot::Mac::TxFrame&, ot::Mac::RxFrame*, ot::Error): Assertion `false' failed.
otbr-agent[298]: 11:36:55.102 [C] Platform------: ------------------ BEGINNING OF CRASH -------------
otbr-agent[298]: 11:36:55.102 [C] Platform------: *** FATAL ERROR: Caught signal: 6 (Aborted)
otbr-agent[298]: 11:36:55.110 [C] Platform------: # 0: /usr/sbin/otbr-agent(+0x20786c) [0x555e46786c]
otbr-agent[298]: 11:36:55.110 [C] Platform------: # 1: /usr/sbin/otbr-agent(+0x2079b0) [0x555e4679b0]
otbr-agent[298]: 11:36:55.110 [C] Platform------: # 2: linux-vdso.so.1 __kernel_rt_sigreturn+0x0 [0xa027b7bc]
otbr-agent[298]: 11:36:55.111 [C] Platform------: # 3: /lib/aarch64-linux-gnu/libc.so.6 gsignal+0xdc [0x9fdcceac]
otbr-agent[298]: 11:36:55.111 [C] Platform------: # 4: /lib/aarch64-linux-gnu/libc.so.6 abort+0x108 [0x9fdb9aa0]
otbr-agent[298]: 11:36:55.111 [C] Platform------: # 5: /lib/aarch64-linux-gnu/libc.so.6(+0x2d478) [0x7f9fdc6478]
otbr-agent[298]: 11:36:55.111 [C] Platform------: # 6: /lib/aarch64-linux-gnu/libc.so.6(+0x2d4dc) [0x7f9fdc64dc]
otbr-agent[298]: 11:36:55.111 [C] Platform------: # 7: /usr/sbin/otbr-agent ot::Mac::SubMac::HandleTransmitDone(ot::Mac::TxFrame&, ot::Mac::RxFrame*, otError)+0xc8 [0x5e4c9bd0]
otbr-agent[298]: 11:36:55.111 [C] Platform------: # 8: /usr/sbin/otbr-agent ot::Radio::Callbacks::HandleTransmitDone(ot::Mac::TxFrame&, ot::Mac::RxFrame*, otError)+0x30 [0x5e563258]
otbr-agent[298]: 11:36:55.111 [C] Platform------: # 9: /usr/sbin/otbr-agent otPlatRadioTxDone+0x68 [0x5e50755c]
otbr-agent[298]: 11:36:55.111 [C] Platform------: #10: /usr/sbin/otbr-agent ot::Spinel::RadioSpinel<ot::Posix::VendorInterface>::TransmitDone(otRadioFrame*, otRadioFrame*, otError)+0x58 [0x5e461518]
otbr-agent[298]: 11:36:55.112 [C] Platform------: #11: /usr/sbin/otbr-agent ot::Spinel::RadioSpinel<ot::Posix::VendorInterface>::ProcessRadioStateMachine()+0x80 [0x5e45f7e4]
otbr-agent[298]: 11:36:55.112 [C] Platform------: #12: /usr/sbin/otbr-agent ot::Spinel::RadioSpinel<ot::Posix::VendorInterface>::Process(void const*)+0x8c [0x5e45d238]
otbr-agent[298]: 11:36:55.112 [C] Platform------: #13: /usr/sbin/otbr-agent platformRadioProcess+0x20 [0x5e45a21c]
otbr-agent[298]: 11:36:55.112 [C] Platform------: #14: /usr/sbin/otbr-agent otSysMainloopProcess+0x28 [0x5e465548]
otbr-agent[298]: 11:36:55.112 [C] Platform------: #15: /usr/sbin/otbr-agent otbr::Ncp::ControllerOpenThread::Process(otSysMainloopContext const&)+0x2c [0x5e56dc78]
otbr-agent[298]: 11:36:55.112 [C] Platform------: #16: /usr/sbin/otbr-agent otbr::MainloopManager::Process(otSysMainloopContext const&)+0x7c [0x5e57284c]
otbr-agent[298]: 11:36:55.112 [C] Platform------: #17: /usr/sbin/otbr-agent otbr::Application::Run()+0x204 [0x5e40ee40]
otbr-agent[298]: 11:36:55.112 [C] Platform------: #18: /usr/sbin/otbr-agent(+0x1b0580) [0x555e410580]
otbr-agent[298]: 11:36:55.113 [C] Platform------: #19: /usr/sbin/otbr-agent main+0x88 [0x5e410740]
otbr-agent[298]: 11:36:55.113 [C] Platform------: #20: /lib/aarch64-linux-gnu/libc.so.6 __libc_start_main+0xe8 [0x9fdb9e18]
otbr-agent[298]: 11:36:55.113 [C] Platform------: #21: /usr/sbin/otbr-agent(+0x1ae8e8) [0x555e40e8e8]
otbr-agent[298]: 11:36:55.113 [C] Platform------: ------------------ END OF CRASH ------------------
[22:07:59] INFO: otbr-agent ended with exit code 256 (signal 6)...
OTBR_FORWARD_INGRESS  all opt    in * out wpan0  ::/0  -> ::/0  
Chain OTBR_FORWARD_INGRESS (0 references)
target     prot opt source               destination         
DROP       all      anywhere             anywhere             PKTTYPE = unicast
DROP       all      anywhere             anywhere             match-set otbr-ingress-deny-src src
ACCEPT     all      anywhere             anywhere             match-set otbr-ingress-allow-dst dst
DROP       all      anywhere             anywhere             PKTTYPE = unicast
ACCEPT     all      anywhere             anywhere            
otbr-ingress-deny-src
otbr-ingress-deny-src-swap
otbr-ingress-allow-dst
otbr-ingress-allow-dst-swap
OTBR_FORWARD_EGRESS  all opt    in wpan0 out *  ::/0  -> ::/0  
Chain OTBR_FORWARD_EGRESS (0 references)
target     prot opt source               destination         
ACCEPT     all      anywhere             anywhere            
[22:07:59] INFO: OTBR firewall teardown completed.
[22:07:59] WARNING: otbr-agent exited with code 134 (by signal 6).
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service otbr-agent-rest-discovery: stopping
s6-rc: info: service zigbeed: stopping
s6-rc: info: service mdns: stopping
s6-rc: info: service otbr-agent-rest-discovery successfully stopped
s6-rc: info: service otbr-agent: stopping
Default: mDNSResponder (Engineering Build) (Jan 24 2024 17:58:11) stopping
[22:07:59] INFO: zigbeed ended with exit code 256 (signal 15)...
s6-rc: info: service zigbeed successfully stopped
[22:07:59] INFO: otbr-agent ended with exit code 256 (signal 15)...
[22:07:59] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service mdns successfully stopped
[22:07:59] INFO: OTBR firewall teardown completed.
[22:07:59] WARNING: otbr-agent exited with code 143 (by signal 15).
s6-rc: info: service otbr-agent successfully stopped
s6-rc: info: service cpcd: stopping
[22:07:59:090338] Info : Endpoint socket #12: Client disconnected. 1 connections
[22:07:59:090423] Info : Client disconnected
[22:07:59:608343] Info : Endpoint socket #12: Client disconnected. 0 connections
[22:07:59:608611] Info : Client disconnected
[22:07:59:795306] Info : Server core cleanup
[22:07:59:795473] Info : Daemon exiting with status EXIT_SUCCESS
Logger buffer size = 28672, highwater mark = 2498 : 8.71%. Lost logs : 0
[22:07:59] INFO: CPC ended with exit code 0 (signal 0)...
s6-rc: info: service cpcd successfully stopped
s6-rc: info: service cpcd-config: stopping
s6-rc: info: service cpcd-config successfully stopped
s6-rc: info: service universal-silabs-flasher: stopping
s6-rc: info: service universal-silabs-flasher successfully stopped
s6-rc: info: service banner: stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by mikenhu** [comment]
I have the same problem. I found that if I temporarily disable then re-enable the OpenThread Border Router" options, Multiprotocol and ZHA work again.

**Comment by macourteau** [comment]
+1, having the same issue. There's a thread discussing it here: https://community.home-assistant.io/t/zha-fails-with-silicon-labs-2-4-4-update-ha-yellow/680593

**Comment by marcelveldt** [comment]
Multiprotocol is no longer actively supported. I suggest you to run zigbee only or thread only instead for a more stable set-up.

**Comment by diegoflyer** [comment]
Dear Guys,
is it confirmed that Silicon Labs Multiprotocol is no more mantained?
@marcelveldt

**Comment by marcelveldt** [comment]
That is correct.

**Comment by oerix** [comment]
> Multiprotocol is no longer actively supported. I suggest you to run zigbee only or thread only instead for a more stable set-up.

Will you be making a official post about this? I had to dig deep to find this info, I would think a separate post is warranted with this important info.

**Comment by jsuelwald** [comment]
> Will you be making a official post about this? I had to dig deep to find this info, I would think a separate post is warranted with this important info.

This is quite important. I think many people brought this because of zigbee and thread

**Comment by puddly** [comment]
This was discussed in the Matter blog back in January: https://www.home-assistant.io/blog/2024/01/25/matter-livestream-blog/#using-home-assistant-yellow-or-home-assistant-skyconnect

**Comment by silabs-grace** [comment]
This issue has been resolved in [GSDK 4.3.3]( https://www.silabs.com/documents/public/release-notes/open-thread-release-notes-2.3.3.0.pdf) release. Specifically: `Bug: 1249346 where the OTBR no longer crashes due to parse error in handleTransmitDone(). This was caused due to RCP not dequeuing the pending transmit commands correctly, which caused it to send invalid information via transmit done.`

**Comment by RichardMawdsley** [comment]
> This issue has been resolved in [GSDK 4.3.3](https://www.silabs.com/documents/public/release-notes/open-thread-release-notes-2.3.3.0.pdf) release. Specifically: `Bug: 1249346 where the OTBR no longer crashes due to parse error in handleTransmitDone(). This was caused due to RCP not dequeuing the pending transmit commands correctly, which caused it to send invalid information via transmit done.`

Excusing my ignorance, but when/how will this be updated to the Addon?

**Comment by reinhapa** [comment]
> > This issue has been resolved in [GSDK 4.3.3](https://www.silabs.com/documents/public/release-notes/open-thread-release-notes-2.3.3.0.pdf) release. Specifically: `Bug: 1249346 where the OTBR no longer crashes due to parse error in handleTransmitDone(). This was caused due to RCP not dequeuing the pending transmit commands correctly, which caused it to send invalid information via transmit done.`
> 
> Excusing my ignorance, but when/how will this be updated to the Addon?

Unfortunately the issue is still not solved. any chance to get the GSDK updated in the add on?

**Comment by Falkvinge** [comment]
Just a ping that I'm also waiting for this to be fixed. As far as I understand, there's no way to roll back once you've installed Matter and Zigbee support together on a Yellow, and having mine crash several times a day is extremely annoying, even with an automatic reboot. Sometimes the automations work, sometimes they don't, and that's not just good enough for me. This bug seems to be the cause of all that (and I have crash logs for anybody interested).

**Comment by puddly** [comment]
@Falkvinge If you actively use Matter *over Thread*, get another border router (you may already have one in your home built into another device!), migrate to it, and then you can disable multiprotocol from the Hardware menu: <https://yellow.home-assistant.io/guides/disable-multiprotocol/>.

**Comment by Falkvinge** [comment]
> @Falkvinge If you actively use Matter _over Thread_, get another border router (you may already have one in your home built into another device!), migrate to it, and then you can disable multiprotocol from the Hardware menu: https://yellow.home-assistant.io/guides/disable-multiprotocol/.

Thank you, this helps. Would connecting a SkyConnect (now called XYZ-1) to the Yellow work as a new border router with seamless transition? How would I then configure it as a Matter-only device, disabling Zigbee, do you have a link handy for this too?

**Comment by puddly** [comment]
Once you uninstall Multiprotocol and revert back to Zigbee, you can select what firmware you want to run on the Yellow itself. If you don't plan on using Zigbee, just select Thread firmware and I believe you can replace your new Thread network's dataset with your old one from the Thread panel:

<img width="340" alt="image" src="https://github.com/user-attachments/assets/2d49b7fc-343c-47b8-8d18-b690b5c450fb">
